development:
  dialect: "mysql"
  database: "tweaser_development"
  host: "127.0.0.1"
  port: "13306"
  user: "root"
  password: "secret"
  encoding: "utf8mb4_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/tweaser_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/tweaser_production?parseTime=true&multiStatements=true&readTimeout=1s"}}